[config]
enable_custom_labels = true

[custom_labels."ğŸ› bug"]
description = """Fixes a bug in the code"""
[custom_labels."ğŸ“„ configuration changes"]
description = """Changes to configuration files"""
[custom_labels."ğŸ§ª tests"]
description = """Adds or modifies tests"""
[custom_labels."âœ¨ enhancement"]
description = """Adds new features or modifies existing ones"""
[custom_labels."ğŸ§¾ documentation"]
description = """Adds or modifies documentation"""
[custom_labels."ğŸ› ï¸ github_actions"]
description = """Adds or modifies GitHub Actions"""
[custom_labels."â¬†ï¸ dependencies"]
description = """Modifications of the project dependencies"""
[custom_labels."ğŸ”„ï¸ sync"]
description = """Additions or modifications to the synchronization code"""
[custom_labels."ğŸ’½ database"]
description = """Additions or modifications to the database code"""
[custom_labels."ğŸŒ web-ui"]
description = """Additions or modifications to the web-ui code"""
